# Generated by Django 5.1.7 on 2025-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='order',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
